services:
  ollama:
    image: ollama/ollama:0.3.11
    networks:
      default:
        ipv4_address: 34.0.0.2
    restart: unless-stopped
    volumes:
      - ./ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    depends_on:
      - ollama
      - stable-diffusion-webui
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
    networks:
      default:
        ipv4_address: 34.0.0.3
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - ./open-webui:/app/backend/data
  stable-diffusion-webui:
    image: universonic/stable-diffusion-webui:minimal
    command: --no-half --no-half-vae --precision full --api --api-auth username:0190ac7d271a75c59bfb-63f44129f3f7
    networks:
      default:
        ipv4_address: 34.0.0.4
    runtime: nvidia
    restart: unless-stopped
    volumes:
      - ./stable-diffusion/inputs:/app/stable-diffusion-webui/inputs
      - ./stable-diffusion/textual_inversion_templates:/app/stable-diffusion-webui/textual_inversion_templates
      - ./stable-diffusion/embeddings:/app/stable-diffusion-webui/embeddings
      - ./stable-diffusion/extensions:/app/stable-diffusion-webui/extensions
      - ./stable-diffusion/models:/app/stable-diffusion-webui/models
      - ./stable-diffusion/localizations:/app/stable-diffusion-webui/localizations
      - ./stable-diffusion/outputs:/app/stable-diffusion-webui/outputs
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    deploy:
      mode: global
      placement:
        constraints:
          - "node.labels.iface != extern"
      restart_policy:
        condition: unless-stopped
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 34.0.0.0/16
