services:
  ollama-nvidia:
    image: ollama/ollama:${OLLAMA_TAG}
    profiles: ["nvidia"]
    environment:
      OLLAMA_CONTEXT_LENGTH: ${OLLAMA_CONTEXT_LENGTH}
    networks:
      default:
        ipv4_address: 34.0.0.2
        aliases:
          - ollama
    group_add:
      - 226
    restart: unless-stopped
    volumes:
      - ${OLLAMA_DATA_DIR}:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  ollama-rocm:
    image: ollama/ollama:${OLLAMA_TAG}-rocm
    profiles: ["rocm"]
    environment:
      OLLAMA_CONTEXT_LENGTH: ${OLLAMA_CONTEXT_LENGTH}
    networks:
      default:
        ipv4_address: 34.0.0.2
        aliases:
          - ollama
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - 44
      - 109
      - 226
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
    volumes:
      - ${OLLAMA_DATA_DIR}:/root/.ollama
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
    networks:
      default:
        ipv4_address: 34.0.0.3
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - ./open-webui:/app/backend/data
  stable-diffusion-webui-nvidia:
    image: ghcr.io/ai-dock/stable-diffusion-webui:latest-cuda
    profiles: ["nvidia"]
    environment:
      WEBUI_ARGS: --no-half --no-half-vae --precision full --api --api-auth ${STABLE_DIFFUSION_API_AUTH}
    networks:
      default:
        ipv4_address: 34.0.0.4
        aliases:
          - stable-diffusion-webui
    group_add:
      - 226
    runtime: nvidia
    restart: unless-stopped
    volumes:
      - ./stable-diffusion/inputs:/app/stable-diffusion-webui/inputs
      - ./stable-diffusion/textual_inversion_templates:/app/stable-diffusion-webui/textual_inversion_templates
      - ./stable-diffusion/embeddings:/app/stable-diffusion-webui/embeddings
      - ./stable-diffusion/extensions:/app/stable-diffusion-webui/extensions
      - ./stable-diffusion/models:/app/stable-diffusion-webui/models
      - ./stable-diffusion/localizations:/app/stable-diffusion-webui/localizations
      - ./stable-diffusion/outputs:/app/stable-diffusion-webui/outputs
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    deploy:
      mode: global
      placement:
        constraints:
          - "node.labels.iface != extern"
      restart_policy:
        condition: unless-stopped
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
  stable-diffusion-webui-rocm:
    image: ghcr.io/ai-dock/stable-diffusion-webui:latest-rocm
    profiles: ["rocm"]
    environment:
      WEBUI_ARGS: --no-half --no-half-vae --precision full --api --api-auth ${STABLE_DIFFUSION_API_AUTH}
    networks:
      default:
        ipv4_address: 34.0.0.4
        aliases:
          - stable-diffusion-webui
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - 44
      - 109
      - 226
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
    volumes:
      - ./stable-diffusion/inputs:/workspace/input
      - ./stable-diffusion/textual_inversion_templates:/workspace/storage/stable_diffusion/models/textual_inversion_templates
      - ./stable-diffusion/embeddings:/workspace/storage/stable_diffusion/models/embeddings
      - ./stable-diffusion/extensions:/workspace/storage/stable_diffusion/models/extensions
      - ./stable-diffusion/models:/workspace/storage/stable_diffusion/models
      - ./stable-diffusion/localizations:/workspace/storage/stable_diffusion/models/localizations
      - ./stable-diffusion/outputs:/workspace/output
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 34.0.0.0/16
